type = 'cylindrical'
depth = 0.5

[bottom]
width = 18.29
height = 18.29
radius = 0.38

[top]
width = 11.81
height = 13.91
radius = 1.52
y-offset = -1.62

[legend.alpha]
size = 4.84
width = 9.45
height = 11.54
y-offset = 0

[legend.symbol]
size = 3.18
width = 9.53
height = 9.56
y-offset = 0.40

[legend.mod]
size = 2.28
width = 9.45
height = 11.30
y-offset = -0.12

[homing]
default = 'scoop'

[homing.scoop]
depth = 1.5

[homing.bar]
width = 3.85
height = 0.4
y-offset = 5.05

[homing.bump]
radius = 0.2
y-offset = -0.2
